package it.me.backyou;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Class holding application entry point
 * Generated by spring boot initializer
 */
@SpringBootApplication
public class BackYouApplication {

    /**
     * Application entry point method
     * Generated by spring boot initializer
     *
     * @param args arguments passed to the application during start
     */
    public static void main(String[] args) {
        SpringApplication.run(BackYouApplication.class, args);
    }

}
